# This is a basic workflow that is manually triggered

name: Publish External Components workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "publish_external_components"
  publish_external_components:
    runs-on: ubuntu-latest
    steps:
      # Check out esphome
      - name: Check out esphome
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            esphome/components/binary_sensor_multi
            esphome/components/delayed
      # Check out esphome-components
      - name: Check out esphome-components
        uses: actions/checkout@v3
        with:
          repository: sa-crespo/esphome-components
          ref: dev
          path: ./esphome_components
          token: ${{ secrets.ESPHOME_TOKEN }}
      # Copy Binary Sensor Multi
      - name: Binary Sensor Multi
        run: |
          mkdir -p ./esphome_components/components/binary_sensor_multi
          cp -R ./esphome/components/binary_sensor_multi ./esphome_components/components
      # Copy Delayed Platform
      - name: Delayed Platform
        run: |
          mkdir -p ./esphome_components/components/delayed
          cp -R ./esphome/components/delayed ./esphome_components/components
      # Push external components
      - name: Push to
        run: |
          cd ./esphome_components
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "External Components"
          git push
